name: Linting and code style

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: py-actions/flake8@v2
        with:
          flake8-version: "6.1.0"
          max-line-length: "88"
          ignore: "E203"
          path: "aintelope tests site"
